### ISSUE TITLE
The evaluation index of the rerun model is lower than the experiment in the paper

### ISSUE THREAD

**Issue by lazy2panda** [Junsu-Cho/TimelyRec_WWW21#1]
I downloaded the github code directly and used the data in the code base to train and evaluate, but the results of val and test are as follows

Val
HR@1   : 0.1409
HR@5   : 0.3788
NDCG@5 : 0.261
HR@10  : 0.5266
NDCG@10: 0.3086

Test
HR@1   : 0.1305
HR@5   : 0.343
NDCG@5 : 0.2376
HR@10  : 0.4861
NDCG@10: 0.2845

This experimental result is lower than the experimental data in the paper：
![image](https://user-images.githubusercontent.com/7948261/126093082-7c3a56f2-946e-4d25-a77f-9db18d66a380.png)

**Comment by Junsu-Cho** [comment]
Hello, 
The training and validation process of the uploaded codes are for the item-timing recommendation, not the item recommendation.
So the results you obtained correspond to Table 3, not Table 2.

Additionally, a more efficient version of the codes including the item recommendation is being prepared for upload, so please refer to it as well later.

**Comment by lazy2panda** [comment]
> Hello,
> The training and validation process of the uploaded codes are for the item-timing recommendation, not the item recommendation.
> So the results you obtained correspond to Table 3, not Table 2.
> 
> Additionally, a more efficient version of the codes including the item recommendation is being prepared for upload, so please refer to it as well later.

thank you
